### ISSUE TITLE
Is there a way to add an edit form to modify records?

### ISSUE THREAD

**Issue by pboling** [blocknotes/tiny_admin#41]
See title.

**Comment by pboling** [comment]
Figured it out!

**Comment by blocknotes** [comment]
Hey @pboling,
at the moment TinyAdmin is mainly proposed for read-only operations.
I would like to propose features it in the future for CRUD operations but I can't provide a road map.
Feel free to share some code if you like, it could help some other user.

**Comment by pboling** [comment]
I'll try to find time to do that.
